services:
  - type: web
    name: woodshot-frontend
    runtime: static
    buildCommand: npm run render-build
    staticPublishPath: ./dist
    routes:
      - type: redirect
        source: /*
        destination: /index.html
        status: 200