
services:
  db:
    image: postgres:15
    container_name: postgres_wood
    environment:
      POSTGRES_USER: woodshot_user
      POSTGRES_PASSWORD: wood_001
      POSTGRES_DB: woodshot_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  adminer:
    image: adminer:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_SERVER: db
    restart: always
    ports: 
      - 8081:8080

volumes:
  db_data: