services:
  - type: web
    name: woodshots-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://woodshothot.com
      - key: BASE_URL
        value: https://api.woodshothot.com
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_oecQ7JkxuDI5@ep-hidden-meadow-ago3spu0-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SECRET_KEY
        value: 5hqsYxORrb9ZR8ClDH7ay4HrhPJ2QJ1feqHqVyOayrg
      - key: ADMIN_PIN
        value: 2017
      - key: JWT_SECRET_KEY
        value: woodshot_secure_jwt_key_2024
      - key: NOWPAYMENTS_API_KEY
        value: NMB5KZX-RZ6MRXB-MP28X3N-4YND23Y
      - key: NOWPAYMENTS_PUBLIC_KEY
        value: cfe33899-95ce-4178-8540-1e1204ab323c
      - key: CLOUDINARY_CLOUD_NAME
        value: djxiszqgd
      - key: CLOUDINARY_API_KEY
        value: 551338185125665
      - key: CLOUDINARY_API_SECRET
        value: z554bu4pErPADN3X76gJ74LBBB4
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        value: colliselect@gmail.com
      - key: MAIL_PASSWORD
        value: ton_app_password_gmail_ici

  - type: web
    name: woodshots-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://api.woodshothot.com
      - key: VITE_FRONTEND_URL
        value: https://woodshothot.com